export const SE_NEW_PRODUCT = "SE_NEW_PRODUCT";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const LOADING_PRODUCT = "LOADING_PRODUCT";

export const PUBLISHED_PRODUCT = "PUBLISHED_PRODUCT";
export const GET_UPDATED_PRODUCT = "GET_UPDATED_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
