export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCT_DATA_SUCCESS = "PRODUCT_DATA_SUCCESS";
export const FAILED_TO_FETCH = "FAILED_TO_FETCH";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ADJUST_QTY = "ADJUST_QTY";
export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";
export const INCREMENT_NUMBER = "INCREMENT_NUMBER";
export const DECREMENT_NUMBER = "DECREMENT_NUMBER";
export const BED_ITEMS = "BED_ITEMS";
export const WOOD_ITEMS = "WOOD_ITEMS";
export const PHONE_ITEMS = "PHONE_ITEMS";
export const TABLE_ITEMS = "TABLE_ITEMS";
export const SHOW_DETAILS = "SHOW_DETAILS";
